# Uncomment these two lines of configuration to
# enable persistent storage in db/kickstart.
################################################
# spring.datasource.url=jdbc:h2:./db/kickstart
# spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=false
upload.directory=${user.home}/uploads
spring.servlet.multipart.max-file-size=100MB

vacationrental.nearby-houses-radius = 20000
vacationrental.cancellation-deadline = 7

salespoint.scheduling.enabled = true

spring.messages.basename=messages
spring.messages.encoding=UTF-8
